### ISSUE TITLE
Error: this._components.remove is not a function

### ISSUE THREAD

**Issue by jkudish** [halt-hammerzeit/react-time-ago#1]
Hi there,

Thanks for this great component 😄 

I am getting an error whenever a `<ReactTimeAgo .../>` instance is removed from the current view (aka gets unmounted):

`Uncaught TypeError: this._components.remove is not a function`

![screen shot 2016-09-05 at 12 19 30 pm](https://cloud.githubusercontent.com/assets/260253/18255878/14cc9b4c-7363-11e6-8839-853aa0e87d3c.png)

Uncommenting that line in your code seems to solve the error without introducing any visible side effects, but that's obviously not a great solution. 

Any ideas?

Thanks!

**Comment by halt-hammerzeit** [comment]
Oh shoot.
Of course, javascript arrays don't have `.remove()` method.
You'll never know how many people were turned off by this error.

It's just my code that does:

```js
Object.defineProperty(Array.prototype, 'remove', 
{
	enumerable: false,
	value: function(element)
	{
		const index = this.indexOf(element)
		if (index >= 0)
		{
			this.splice(index, 1)
		}
		return this
	}
})
```

I've fixed the issue in the latest release, try it

```
npm install react-time-ago@latest --save
```

**Comment by jkudish** [comment]
Thanks for the awesome fast fix! 

Works as expected now 👍
